### ISSUE TITLE
[BUG][Proxy Authentication] Failed to skip default demo configuration

### ISSUE THREAD

**Issue by alborotogarcia** [opensearch-project/opensearch-devops#46]
**Describe the bug**
Unable to auth through internal proxy, or change internal users. Demo configuration gets applied always.

**To Reproduce**
1. Template the helm chart to a yaml file
2. Set config.yml as a configmap subpath from the docs 
2. Mounted it at /usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml or /usr/share/opensearch/config/config.yml
3. I can see it on the nodes, but doesn't propagate any configuration at all.
4. Tried as well to it on values configfile at the config field eg
```  
config:
  config.yml:
```

I always get the following

```
opensearch-cluster-master-0 opensearch io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f20485454502f312e310d0a486f73743a20656c61737469632e616c626f726f746f2e6c6976650d0a557365722d4167656e743a204d6f7a696c6c612f352e30202857696e646f7773204e542031302e303b2072763a37382e3029204765636b6f2f32303130303130312046697265666f782f37382e300d0a4163636570743a20746578742f68746d6c2c6170706c69636174696f6e2f7868746d6c2b786d6c2c6170706c69636174696f6e2f786d6c3b713d302e392c696d6167652f776562702c2a2f2a3b713d302e380d0a4163636570742d456e636f64696e673a20677a69700d0a4163636570742d4c616e67756167653a20656e2d55532c656e3b713d302e350d0a43646e2d4c6f6f703a20636c6f7564666c6172650d0a43662d436f6e6e656374696e672d49703a20323630353a363430303a33303a663035313a353662393a653162313a346138653a313463660d0a43662d4970636f756e7472793a204c550d0a43662d5261793a20363830353034333532383939303565642d4652410d0a43662d56697369746f723a207b22736368656d65223a226874747073227d0d0a436f6f6b69653a2061757468656c69615f73657373696f6e3d67784e796c685a67496648486c6277676c49494d49586262416a5a6671756c6c0d0a526566657265723a2068747470733a2f2f617574682e616c626f726f746f2e6c6976652f0d0a52656d6f74652d456d61696c3a20616c626f726f746f67617263696137373740676d61696c2e636f6d0d0a52656d6f74652d47726f7570733a200d0a52656d6f74652d4e616d653a200d0a52656d6f74652d557365723a20616c626f726f746f0d0a557067726164652d496e7365637572652d52657175657374733a20310d0a582d466f727761726465642d466f723a203136322e3135382e39312e350d0a582d466f727761726465642d486f73743a20656c61737469632e616c626f726f746f2e6c6976650d0a582d466f727761726465642d506f72743a203434330d0a582d466f727761726465642d50726f746f3a2068747470730d0a582d466f727761726465642d5365727665723a207472616566696b2d3937623434623739342d386a6d706a0d0a582d5265616c2d49703a203136322e3135382e39312e350d0a0d0a
```

5. Also at securityConfig

**Expected behavior**

**Component**
Please list all components currently enabled. (Helm, etc.)

Configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-cluster-master-config
  labels:
    heritage: "Helm"
    release: "opensearch"
    chart: "opensearch"
    app: "opensearch-cluster-master"
data:
  config.yml: |
    _meta:
      config_version: 2
      type: config
    config:
      dynamic:
        authc:
          proxy_auth_domain:
            authentication_backend:
              type: noop
            http_authenticator:
              challenge: false
              config:
                roles_header: Remote-Groups
                user_header: Remote-User
              type: proxy
            http_enabled: true
            order: 0
            transport_enabled: true
        http:
          anonymous_auth_enabled: false
          xff:
            enabled: true
            internalProxies: xxx.xxx.xxx.xxx
            remoteIpHeader: x-forwarded-for
```

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Version 1.0.0

**Additional context**
