### ISSUE TITLE
[BUG][opensearch] helm chart can not be deployed without ssl

### ISSUE THREAD

**Issue by killerquitsche** [opensearch-project/opensearch-devops#55]
**Describe the bug**
The failure code is:
```yaml
config:
  opensearch_dashboards.yml:
    server:
        name: dashboards
        host: 0.0.0.0
    ## Dashboards TLS Config
      ssl:
        enabled: false
        key: /usr/share/opensearch-dashboards/certs/dashboards-key.pem
        certificate: /usr/share/opensearch-dashboards/certs/dashboards-crt.pem
    opensearch.ssl.certificateAuthorities: /usr/share/opensearch-dashboards/certs/dashboards-root-ca.pem
```
Error Msg:
> {"type":"log","@timestamp":"2021-08-26T05:34:48Z","tags":["fatal","root"],"pid":1,"message":"{ Error: ENOENT: no such file or directory, open '/usr/share/opensearch-dashboards/certs/dashboards-key.pem'\n    at Object.openSync (fs.js:443:3)\n    at readFileSync (fs.js:343:35)\n    at readFile (/usr/share/opensearch-dashboards/src/core/server/http/ssl_config.js:181:31)\n    at new SslConfig (/usr/share/opensearch-dashboards/src/core/server/http/ssl_config.js:131:18)\n    at new HttpConfig (/usr/share/opensearch-dashboards/src/core/server/http/http_config.js:175:16)\n    at MapSubscriber.HttpService.config$.pipe [as project] (/usr/share/opensearch-dashboards/src/core/server/http/http_service.js:61:177)\n    at MapSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/map.js:49:35)\n    at MapSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at CombineLatestSubscriber.notifyNext (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/observable/combineLatest.js:97:34)\n    at InnerSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/InnerSubscriber.js:28:21)\n    at InnerSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at DistinctUntilChangedSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)\n    at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/map.js:55:26)\n  errno: -2,\n  syscall: 'open',\n  code: 'ENOENT',\n  path: '/usr/share/opensearch-dashboards/certs/dashboards-key.pem' }"}
> FATAL  Error: ENOENT: no such file or directory, open '/usr/share/opensearch-dashboards/certs/dashboards-key.pem'

**To Reproduce**
Just try to install latest opensearch helm chart with these different configurations:
**Code config 1:**
```yaml
config:
  opensearch_dashboards.yml:
    server:
      name: dashboards
      host: 0.0.0.0
      ## Dashboards TLS Config
    #   ssl:
    #     enabled: false
    #     key: /usr/share/opensearch-dashboards/certs/dashboards-key.pem
    #     certificate: /usr/share/opensearch-dashboards/certs/dashboards-crt.pem
    # opensearch.ssl.certificateAuthorities: /usr/share/opensearch-dashboards/certs/dashboards-root-ca.pem
```

**Code config 2:**
```yaml
config:
  opensearch_dashboards.yml:
    server:
      name: dashboards
      host: 0.0.0.0
      ## Dashboards TLS Config
      ssl:
        enabled: false
    #     key: /usr/share/opensearch-dashboards/certs/dashboards-key.pem
    #     certificate: /usr/share/opensearch-dashboards/certs/dashboards-crt.pem
    # opensearch.ssl.certificateAuthorities: /usr/share/opensearch-dashboards/certs/dashboards-root-ca.pem
```

**Code config 3:**
```yaml
config:
  opensearch_dashboards.yml:
    server:
      name: dashboards
      host: 0.0.0.0
      ## Dashboards TLS Config
      ssl:
        enabled: false
        key: ""
        certificate: "" 
    opensearch.ssl.certificateAuthorities: ""
```

**Expected behavior**
Should be able to install opensearch on Kubernetes Cluster

**Component**
Please list all components currently enabled. (Helm, etc.)

**Screenshots**
None

**Host/Environment (please complete the following information):**
 - OS: Linux -> Kubernetes Cluster with Flatcar OS
 - Version 1.0.0
 - Helm version: 3.5.4

**Additional context**
[Comment under the commit **220a62f** with further error messages.](https://github.com/opensearch-project/opensearch-devops/commit/220a62fa3bc0122872c680eaf18021c589c92c82#commitcomment-55451898)
