### ISSUE TITLE
[BUG][Helm] If cluster name is set anything apart from "opesearch-cluster", getting an error OpenSearch Security not initialised.

### ISSUE THREAD

**Issue by jasodeep** [opensearch-project/opensearch-devops#65]
**Describe the bug**
I tried deploying OpenSearch using the helm chart, it’s working fine when the cluster name is set to default opesearch-cluster, but when it’s set to something custom, it’s throwing error -
`OpenSearch Security not initialised`

**Values which resulting error -**
```
clusterName: "foobar"
nodeGroup: "master"
masterService: "foobar-master"
config:
  opensearch.yml:
    cluster.name: foobar-cluster
```

**Working Values**
```
clusterName: "opensearch-cluster"
nodeGroup: "master"
masterService: "opensearch-cluster-master"
config:
  opensearch.yml:
    cluster.name: opensearch-cluster
```

**Comment by TheAlgo** [comment]
@jasodeep It looks like your `clusterName` is not same. If you make it `foobar-cluster` in both the cases it should work ideally.

**Comment by jasodeep** [comment]
@TheAlgo aah ! that was a typo while putting the code here.
anyway, I just retried with the following value got the same issue -

`OpenSearch Security not initialised`

```
clusterName: "foobar"
nodeGroup: "master"

# The service that non master groups will try to connect to when joining the cluster
# This should be set to clusterName + "-" + nodeGroup for your master group
masterService: "foobar-master"

# OpenSearch roles that will be applied to this nodeGroup
# These will be set as environment variables. E.g. node.master=true
roles:
  master: "true"
  ingest: "true"
  data: "true"
  remote_cluster_client: "true"

replicas: 3
minimumMasterNodes: 1

majorVersion: "1.0.0"

# Allows you to add any config files in {{ .Values.configPath }}/config
opensearchHome: /usr/share/opensearch
# such as opensearch.yml and log4j2.properties
config:
  opensearch.yml:
    cluster.name: foobar

    # Bind to all interfaces because we don't know what IP address Docker will assign to us.
    network.host: 0.0.0.0
```

do I need to update the cluster name in some other place also, apart from  **cluster.name** and **clusterName** ?
